export const POST_CATEGORIES = [
  { value: "", label: "-- Select Category --" },
  { value: "vehicles", label: "Vehicles" },
  { value: "real_estate", label: "Real Estate" },
  { value: "electronics", label: "Electronics" },
  { value: "mobiles", label: "Mobile Phones & Accessories" },
  { value: "computers", label: "Computers & Laptops" },
  { value: "fashion", label: "Fashion & Clothing" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "furniture", label: "Furniture & Home Decor" },
  { value: "home_appliances", label: "Home Appliances" },
  { value: "pets", label: "Pets & Animals" },
  { value: "services", label: "Services" },
  { value: "jobs", label: "Jobs" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "games", label: "Video Games & Consoles" },
  { value: "collectibles", label: "Collectibles & Art" },
  { value: "books", label: "Books, Movies & Music" },
  { value: "baby", label: "Baby & Kids" },
  { value: "industrial", label: "Heavy Equipment" },
  { value: "business", label: "Business Equipment" },
  { value: "tickets", label: "Tickets & Vouchers" },
  { value: "education", label: "Education & Classes" },
  { value: "food", label: "Food & Drinks" },
  { value: "hobbies", label: "Hobbies & Crafts" },
  { value: "other", label: "Other" },
];
