import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header/Header";
import { Roboto } from "next/font/google";
import { QueryProvider } from "@/providers/QueryProvider";
import Sidebar from "@/components/layout/sidebars/Sidebar";

export const metadata: Metadata = {
  title: "Tager",
  description: "Generated by create next app",
};

const robotoFont = Roboto({ variable: "--font-roboto" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" className="h-full">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`w-full h-full flex flex-col  relative bg-bg ${robotoFont.className}`}
      >
        <QueryProvider>
          <Header />
          <div className="flex ">
            <main className={`container mx-auto  pt-4  flex-1 h-full`}>
              {children}
            </main>
            <Sidebar />
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
