import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header/Header";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Tager",
  description: "Generated by create next app",
};

const robotoFont = Roboto({ variable: "--font-roboto" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" className="h-full">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`w-full h-full flex flex-col  relative bg-bg ${robotoFont.className}`}
      >
        <Header />
        <div className="flex h-full">
          <main className={`container mx-auto mb-5 h-full`}>{children}</main>
          {/* <Sidebar /> */}
        </div>
      </body>
    </html>
  );
}
