import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header/Header";
import { Roboto } from "next/font/google";
import Sidebar from "@/components/layout/sidebars/Sidebar";

export const metadata: Metadata = {
  title: "Tager",
  description: "Generated by create next app",
};

const robotoFont = Roboto({ variable: "--font-roboto" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-full flex bg-bg ${robotoFont.className}`}>
        <div className="flex flex-col w-full bg-bg">
          <Header />
          <main className={`container mx-auto mb-5`}>{children}</main>
        </div>
        <Sidebar />
      </body>
    </html>
  );
}
